name: Build Windows Executable

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Push events to tags matching v*, e.g., v1.0, v20.15.10
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        pip install uv
        
    - name: Setup Python environment
      run: |
       uv venv
       export UV_LINK_MODE=copy
       uv pip install -r requirements.txt
       uv pip install pyinstaller

    - name: Set version info
      id: get_version
      run: |
        python -c "import pydecoder; print('VERSION=' + pydecoder.__version__)" >> $env:GITHUB_OUTPUT
      shell: pwsh
        
    - name: Build executable
      run: |
        python -m PyInstaller --onefile --noconsole --name PYDecoder main.py
    
    - name: Rename executable with version
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        Rename-Item -Path "dist/PYDecoder.exe" -NewName "PYDecoder-v$version.exe"
      shell: pwsh
        
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: PYDecoder-Windows
        path: dist/PYDecoder-v*.exe
    
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          dist/PYDecoder-v*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}